const itemTypes = {
  FETCH_ITEM_START: "FETCH_ITEM_START",
  FETCH_ITEM_FAILURE: "FETCH_ITEM_FAILURE",
  FETCH_SINGLE_ITEM_SUCCESS: "FETCH_SINGLE_ITEM_SUCCESS",
  FETCH_All_ITEM_SUCCESS: "FETCH_All_ITEM_SUCCESS",
  FETCH_All_ITEM_BY_PAGE_SUCCESS: "FETCH_All_ITEM_BY_PAGE_SUCCESS"
};

export default itemTypes;
