const userAdminTypes = {
  FETCH_USER_ADMIN_START: "FETCH_USER_ADMIN_START",
  FETCH_USER_ADMIN_FAILURE: "FETCH_USER_ADMIN_FAILURE",
  FETCH_SINGLE_USER_ADMIN_SUCCESS: "FETCH_SINGLE_USER_ADMIN_SUCCESS",
  FETCH_All_USER_ADMIN_SUCCESS: "FETCH_All_USER_ADMIN_SUCCESS",
  FETCH_All_USER_ADMIN_BY_PAGE_SUCCESS: "FETCH_All_USER_ADMIN_BY_PAGE_SUCCESS"
};

export default userAdminTypes;
