const cartTypes = {
  FETCH_ORDER_START: "FETCH_ORDER_START",
  FETCH_ORDER_FAILURE: "FETCH_ORDER_FAILURE",
  FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
  FETCH_ORDER_INFO_SUCCESS: "FETCH_ORDER_INFO_SUCCESS",
  FETCH_ORDER_HISTORY: "FETCH_ORDER_HISTORY"
};

export default cartTypes;
