const userTypes = {
  ADD_USER: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
  LOGIN_USER: "LOGIN_USER",
  PERSIST_USER: "PERSIST_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGGED_IN: "LOGGED_IN"
};

export default userTypes;
