const orderAdminTypes = {
  FETCH_ORDER_ADMIN_START: "FETCH_ORDER_ADMIN_START",
  FETCH_ORDER_ADMIN_FAILURE: "FETCH_ORDER_ADMIN_FAILURE",
  FETCH_SINGLE_ORDER_ADMIN_SUCCESS: "FETCH_SINGLE_ORDER_ADMIN_SUCCESS",
  FETCH_All_ORDER_ADMIN_SUCCESS: "FETCH_All_ORDER_ADMIN_SUCCESS",
  FETCH_All_ORDER_ADMIN_BY_PAGE_SUCCESS: "FETCH_All_ORDER_ADMIN_BY_PAGE_SUCCESS"
};

export default orderAdminTypes;
